韓國

cmake 
-DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.0/modules 
-DWITH_CUDA=ON 
-DCUDA_FAST_MATH=1 
-DBUILD_EXAMPLES=ON  
-DBUILD_opencv_python3=ON 
-DPYTHON3_INCLUDE_DIR2=/usr/include/python3.6m 
-DPYTHON3_NUMPY_INCLUDE_DIRS=/usr/lib/python3/dist-packages/numpy/core/include 
-DCUDA_ARCH_BIN="5.3" 
-DCUDA_ARCH_PTX=""  
-DBUILD_TESTS=OFF 
-DBUILD_PERF_TESTS=OFF 
-DBUILD_EXAMPLES=OFF ..


日本

cmake 
-D WITH_CUDA=ON 
-D CUDA_ARCH_BIN="5.3" 
-D CUDA_ARCH_PTX="" 
-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.0/modules 
-D WITH_GSTREAMER=ON 
-D WITH_LIBV4L=ON 
-D BUILD_opencv_python2=ON 
-D BUILD_opencv_python3=ON 
-D BUILD_TESTS=OFF 
-D BUILD_PERF_TESTS=OFF 
-D BUILD_EXAMPLES=OFF 
-D CMAKE_BUILD_TYPE=RELEASE 
-D CMAKE_INSTALL_PREFIX=/usr/local ..


Jack opencv4 + Qt5

sudo cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D ENABLE_NEON=ON \
    -D ENABLE_VFPV3=ON \
    -D WITH_FFMPEG=ON \
    -D BUILD_TESTS=OFF \
    -D WITH_QT=ON \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D INSTALL_PYTHON_EXAMPLES=OFF \
    -D INSTALL_C_EXAMPLES=OFF \
    -D BUILD_EXAMPLES=OFF ..


成功版本，去掉ENABLE_VFPV3=ON

sudo cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
-D ENABLE_NEON=ON \
-D WITH_CUDA=ON \
-DCUDA_FAST_MATH=1 \
-D CUDA_ARCH_BIN="5.3" \
-D CUDA_ARCH_PTX="" \
-D WITH_GSTREAMER=ON \
-D WITH_LIBV4L=ON \
-D BUILD_opencv_python2=ON \
-D BUILD_opencv_python3=ON \
-D WITH_FFMPEG=ON \
-D BUILD_TESTS=OFF \
-D WITH_QT=ON \
-D OPENCV_ENABLE_NONFREE=ON \
-D BUILD_PERF_TESTS=OFF \
-D INSTALL_PYTHON_EXAMPLES=OFF \
-D INSTALL_C_EXAMPLES=OFF \
-D BUILD_EXAMPLES=OFF ..

